

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudDataMar.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CloudDataContainer : DbContext
{
    public CloudDataContainer()
        : base("name=CloudDataContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<data_accessory_info> data_accessory_info { get; set; }

    public virtual DbSet<data_announce_info> data_announce_info { get; set; }

    public virtual DbSet<data_application> data_application { get; set; }

    public virtual DbSet<data_detail_info> data_detail_info { get; set; }

    public virtual DbSet<data_info> data_info { get; set; }

    public virtual DbSet<data_special> data_special { get; set; }

    public virtual DbSet<data_type_info> data_type_info { get; set; }

    public virtual DbSet<user_info> user_info { get; set; }

    public virtual DbSet<user_role> user_role { get; set; }

    public virtual DbSet<data_statistics> data_statistics { get; set; }

}

}

