
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudDataMar.Model
{

using System;
    using System.Collections.Generic;
    
public partial class data_type_info
{

    public data_type_info()
    {

        this.data_info = new HashSet<data_info>();

    }


    public int ID { get; set; }

    public string Data_Type_Name { get; set; }

    public string Data_Type_Image { get; set; }

    public string Data_Type_Describe { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.DateTime> UpdateDateTime { get; set; }

    public Nullable<int> Data_Type_OrderNum { get; set; }



    public virtual ICollection<data_info> data_info { get; set; }

}

}
