
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudDataMar.Model
{

using System;
    using System.Collections.Generic;
    
public partial class data_statistics
{

    public long id { get; set; }

    public long data_catagory { get; set; }

    public long item_id { get; set; }

    public long browse_quantity { get; set; }

    public long download_quantity { get; set; }

}

}
