
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudDataMar.Model
{

using System;
    using System.Collections.Generic;
    
public partial class data_detail_info
{

    public data_detail_info()
    {

        this.data_accessory_info = new HashSet<data_accessory_info>();

    }


    public int ID { get; set; }

    public Nullable<int> Data_Info_ID { get; set; }

    public string Data_Detail_Name { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.DateTime> UpdateDateTime { get; set; }

    public string Data_Detail_Source { get; set; }

    public string Data_Detail_Script { get; set; }

    public string Data_Detail_Desc { get; set; }

    public Nullable<int> Data_IsPublish { get; set; }

    public Nullable<int> Data_IsOutSide { get; set; }

    public string SearchColumns1 { get; set; }

    public string SearchColumns2 { get; set; }

    public string SearchColumns3 { get; set; }

    public string SearchContidion1 { get; set; }

    public string SearchContidion2 { get; set; }

    public string SearchContidion3 { get; set; }

    public string SearchColumns4 { get; set; }

    public string SearchColumns5 { get; set; }

    public string SearchColumns6 { get; set; }

    public string SearchContidion4 { get; set; }

    public string SearchContidion5 { get; set; }

    public string SearchContidion6 { get; set; }



    public virtual ICollection<data_accessory_info> data_accessory_info { get; set; }

    public virtual data_info data_info { get; set; }

}

}
