
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudDataMar.Model
{

using System;
    using System.Collections.Generic;
    
public partial class data_info
{

    public data_info()
    {

        this.data_detail_info = new HashSet<data_detail_info>();

    }


    public int ID { get; set; }

    public Nullable<int> Data_Type_ID { get; set; }

    public string Data_Info_Name { get; set; }

    public string Data_Info_Image { get; set; }

    public string Data_Info_Describe { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.DateTime> UpdateDateTime { get; set; }



    public virtual ICollection<data_detail_info> data_detail_info { get; set; }

    public virtual data_type_info data_type_info { get; set; }

}

}
