
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace CloudDataMar.Model
{

using System;
    using System.Collections.Generic;
    
public partial class user_info
{

    public int ID { get; set; }

    public string UserID { get; set; }

    public string UserName { get; set; }

    public string UserPassword { get; set; }

    public Nullable<int> UserLevel { get; set; }

    public string TelePhone { get; set; }

    public string EMail { get; set; }

    public string Position { get; set; }

    public string WorkUnits { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public Nullable<System.DateTime> UpdateDateTime { get; set; }

}

}
